# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30, unique=True, verbose_name='\u7c7b\u522b\u540d\u79f0')),
            ],
            options={
                'db_table': 't_category',
                'verbose_name_plural': '\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('desc', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('creatime', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Category', verbose_name='\u6240\u5c5e\u7c7b\u522b')),
            ],
            options={
                'db_table': 't_post',
                'verbose_name_plural': '\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=30, unique=True, verbose_name='\u6807\u7b7e\u540d')),
            ],
            options={
                'db_table': 't_tag',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blogs.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
